qlib_init:
    provider_uri: "~/.qlib/qlib_data/cn_data"
    region: cn
market: &market csi300
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2024-05-20
    fit_start_time: 2008-01-01
    fit_end_time: 2022-12-31
    instruments: *market
port_analysis_config: &port_analysis_config
    executor:
            class: SimulatorExecutor
            module_path: qlib.backtest.executor
            kwargs:
                time_per_step: week
                generate_portfolio_metrics: true
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 20
            n_drop: 5
    backtest:
        start_time: 2023-07-31
        end_time: 2024-04-30
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: XGBModel
        module_path: qlib.contrib.model.xgboost
        kwargs:
            eval_metric: rmse
            colsample_bytree: 0.8879
            eta: 0.0421
            max_depth: 8
            n_estimators: 647
            subsample: 0.8789
            nthread: 20
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: DailyHandler
                module_path: qlib.contrib.data.daily_handler
                kwargs: *data_handler_config
            segments:
                train: [2008-01-01, 2022-12-31]
                valid: [2023-01-01, 2023-12-31]
                test: [2024-01-01, 2024-05-20]
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
